"""Generate, build, and optionally flash an MCU-normalized FSR1 firmware.

Workflow:
1. Run the raw FSR1 firmware and capture zero plus full-pressure calibration
   with live_fsr_heatmap.py.
2. Close every program that owns COM9.
3. Run:
       python build_flash_normalized_fsr1.py --flash

The generated STM32 firmware maps every calibrated cell to the 12-bit range
0..4095 before transmitting it to the Teensy.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path


ROWS = 16
COLS = 16
ADC_MAX = 0x0FFF
SCRIPT_DIRECTORY = Path(__file__).resolve().parent
FIRMWARE_ROOT = SCRIPT_DIRECTORY.parents[2]
DEFAULT_CALIBRATION = SCRIPT_DIRECTORY / "data" / "calibration" / "fsr1.json"
DEFAULT_PROJECT = FIRMWARE_ROOT / "stm32" / "applications" / "fsr1"
DEFAULT_BUILD = Path(r"D:\study\programming\builds\ESKIN_FSR1_NORMALIZED")


def parse_matrix(value: object, name: str) -> list[list[int]]:
    if not isinstance(value, list) or len(value) != ROWS:
        raise ValueError(f"{name} must contain {ROWS} rows")
    result: list[list[int]] = []
    for row_index, row in enumerate(value):
        if not isinstance(row, list) or len(row) != COLS:
            raise ValueError(
                f"{name}[{row_index}] must contain {COLS} columns"
            )
        converted: list[int] = []
        for column_index, sample in enumerate(row):
            if not isinstance(sample, (int, float)) or not math.isfinite(sample):
                raise ValueError(
                    f"{name}[{row_index}][{column_index}] is not finite"
                )
            rounded = int(round(sample))
            if not 0 <= rounded <= ADC_MAX:
                raise ValueError(
                    f"{name}[{row_index}][{column_index}]={rounded} "
                    f"is outside 0..{ADC_MAX}"
                )
            converted.append(rounded)
        result.append(converted)
    return result


def load_endpoints(
    path: Path,
    minimum_calibration_frames: int,
) -> tuple[list[list[int]], list[list[int]], str, int, int]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if payload.get("version") != 1:
        raise ValueError("calibration JSON version must be 1")
    if payload.get("rows") != ROWS or payload.get("cols") != COLS:
        raise ValueError("calibration JSON dimensions must be 16 x 16")
    if payload.get("zero") is None:
        raise ValueError("zero calibration is missing")
    if payload.get("full") is None:
        raise ValueError(
            "full-pressure calibration is missing; run Calibrate full first"
        )
    zero_frames = payload.get("zero_frames")
    full_frames = payload.get("full_frames")
    if not isinstance(zero_frames, int) or zero_frames < minimum_calibration_frames:
        raise ValueError(
            "zero calibration was not captured with the required "
            f"{minimum_calibration_frames} frames; recapture Calibrate zero"
        )
    if not isinstance(full_frames, int) or full_frames < minimum_calibration_frames:
        raise ValueError(
            "full-pressure calibration was not captured with the required "
            f"{minimum_calibration_frames} frames; recapture Calibrate full"
        )
    return (
        parse_matrix(payload["zero"], "zero"),
        parse_matrix(payload["full"], "full"),
        str(payload.get("updated_at", "unknown")),
        zero_frames,
        full_frames,
    )


def format_c_matrix(name: str, matrix: list[list[int]]) -> str:
    lines = [f"static const uint16_t {name}[16][16] = {{"]
    for row in matrix:
        values = ", ".join(f"{value}U" for value in row)
        lines.append(f"  {{{values}}},")
    lines.append("};")
    return "\n".join(lines)


def generate_header(
    path: Path,
    zero: list[list[int]],
    full: list[list[int]],
    minimum_span: int,
    calibration_source: Path,
    calibration_updated_at: str,
    zero_frames: int,
    full_frames: int,
) -> tuple[int, int, int]:
    spans = [
        abs(full[row][column] - zero[row][column])
        for row in range(ROWS)
        for column in range(COLS)
    ]
    invalid = sum(span < minimum_span for span in spans)
    source_digest = hashlib.sha256(calibration_source.read_bytes()).hexdigest()
    generated_at = datetime.now(timezone.utc).isoformat()
    text = f"""#ifndef FSR_MCU_CALIBRATION_H
#define FSR_MCU_CALIBRATION_H

#include <stdint.h>

/*
 * AUTO-GENERATED by build_flash_normalized_fsr1.py.
 * Generated: {generated_at}
 * Calibration updated: {calibration_updated_at}
 * Calibration SHA-256: {source_digest}
 * Zero capture: {zero_frames} frames
 * Full capture: {full_frames} frames
 * Cells with |full-zero| below {minimum_span} counts output zero.
 */
#define FSR_MCU_CALIBRATION_VALID 1U
#define FSR_MCU_CALIBRATION_MIN_SPAN {minimum_span}U

{format_c_matrix("fsr_mcu_zero", zero)}

{format_c_matrix("fsr_mcu_full", full)}

#endif /* FSR_MCU_CALIBRATION_H */
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(text, encoding="utf-8", newline="\n")
    temporary.replace(path)
    return min(spans), max(spans), invalid


def run(command: list[str], cwd: Path | None = None) -> None:
    print("+", subprocess.list2cmdline(command), flush=True)
    subprocess.run(command, cwd=cwd, check=True)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--calibration-file",
        type=Path,
        default=DEFAULT_CALIBRATION,
    )
    parser.add_argument("--project", type=Path, default=DEFAULT_PROJECT)
    parser.add_argument("--build-dir", type=Path, default=DEFAULT_BUILD)
    parser.add_argument("--minimum-span", type=int, default=50)
    parser.add_argument(
        "--minimum-calibration-frames",
        type=int,
        default=250,
        help=(
            "Require both zero and full maps to contain at least this many "
            "captured frames (default: 250, approximately 10 seconds at 25 fps)"
        ),
    )
    parser.add_argument(
        "--require-all-valid",
        action="store_true",
        help="Stop if any cell has |full-zero| below --minimum-span",
    )
    parser.add_argument(
        "--build",
        action="store_true",
        help="Build after generating the calibration header",
    )
    parser.add_argument(
        "--flash",
        action="store_true",
        help="Build and flash through pyOCD after generating the header",
    )
    parser.add_argument("--probe", default="LU_2022_8888")
    parser.add_argument("--target", default="stm32g474cetx")
    parser.add_argument("--frequency", default="10k")
    args = parser.parse_args()
    if args.minimum_span < 1 or args.minimum_span > ADC_MAX:
        parser.error("--minimum-span must be within 1..4095")
    if args.minimum_calibration_frames < 1:
        parser.error("--minimum-calibration-frames must be at least 1")
    return args


def main() -> int:
    args = parse_args()
    calibration_path = args.calibration_file.resolve()
    project = args.project.resolve()
    build_directory = args.build_dir.resolve()
    header = project / "Core" / "Inc" / "fsr_mcu_calibration.h"

    try:
        zero, full, updated_at, zero_frames, full_frames = load_endpoints(
            calibration_path,
            args.minimum_calibration_frames,
        )
        span_min, span_max, invalid = generate_header(
            header,
            zero,
            full,
            args.minimum_span,
            calibration_path,
            updated_at,
            zero_frames,
            full_frames,
        )
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"Calibration generation failed: {error}", file=sys.stderr)
        return 2

    print(f"Generated: {header}")
    print(
        f"Calibration captures: zero={zero_frames} frames, "
        f"full={full_frames} frames"
    )
    print(
        f"Calibration span: {span_min}..{span_max}; "
        f"invalid cells: {invalid}/{ROWS * COLS}"
    )
    if invalid and args.require_all_valid:
        print(
            "Refusing to build because --require-all-valid was requested",
            file=sys.stderr,
        )
        return 3
    if invalid:
        print(
            "Warning: invalid cells will be transmitted as zero pressure",
            file=sys.stderr,
        )

    if args.build or args.flash:
        toolchain = project / "cmake" / "gcc-arm-none-eabi.cmake"
        run(
            [
                "cmake",
                "-S",
                str(project),
                "-B",
                str(build_directory),
                "-G",
                "Ninja",
                "-DCMAKE_BUILD_TYPE=Release",
                "--toolchain",
                str(toolchain),
            ]
        )
        run(["cmake", "--build", str(build_directory), "--parallel"])

    if args.flash:
        elf = build_directory / "ESKIN_STM32.elf"
        run(
            [
                "pyocd",
                "flash",
                "-u",
                args.probe,
                "-t",
                args.target,
                "-f",
                args.frequency,
                "-M",
                "under-reset",
                "-e",
                "sector",
                str(elf),
            ]
        )
        print("FSR1 MCU-normalized firmware programmed successfully")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
